# alzamon.art config.yml file
# ==============================

#jekyll seo tag values
title: Alzamon - Children's Illustration Portfolio, All-Ages Comics and Sketchbook by Alberto Gonzalez
description: Illustration portfolio and blog focused on kids-oriented illustration, character design, all-ages comics and related subjects for entertainment and educative purposes by Costa Rica-based illustrator Alberto Gonzalez (Alzamon).
keywords:
  - illustration
  - character design
  - comics
  - graphic novels
  - costa rica
  - illustrator
  - costa rican author
  - animation
  - 2d animation
  - 3d animation
  - site critiques
  - website analysis
  - custom character design
  - costa rican artist
  - blog
  - newsletter
  - subscribe to newsletter
  - creative services
  - portfolio
  - kids comics
  - kids comics portfolio
  - childrens illustration
  - graphic novels for kids
  - illustration portfolio
  - character design portfolio
author:
  name: Alzamon (Alberto Gonzalez)
  twitter: alzamonart
  image: /assets/images/azm-avatar-twitter.png
twitter:
  username: alzamonart  
social:
  name: Alzamon - Alberto Gonzalez, Children's Illustrator and Character Designer
  links:
    - https://twitter.com/alzamonart
    - https://instagram.com/alzamonart
    - https://deviantart.com/alzamonart
    - https://behance.net/alzamon

# base URL values - use 'bundle exec jekyll build' (not serve) to generate correct canonical URLs for upload
baseurl: ""
url: "https://alzamon.art"
encoding: UTF-8

#include generated htaccess file for remote hosting
#include: 
#  - .htaccess

#exclude files from export
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package-lock.json
  - package.json
  - README.md

#gather all collections under /portfolio
# collections_dir: portfolio

collections:
  portfolio:
    output: true 
    permalink: "/:collection/:name/"
  comics:
    output: true
    permalink: "/:collection/:name/"
  agents:
    output: true
    permalink: "/:collection/:name/"


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "Alzamon — Visual Creations, Children's Illustration, Comics, Animation and Creative Services by Alberto Gonzalez"
  - scope:
      type: agentsItem
    values:
      layout: "minimal"
      path: /assets/images/agentAccess/


# keep these files from regenerating:
# exclude: [/agents]
# keep_files: [/agents]

#portfolio categories
category-list: [homepage,illustration,characterdesign,comics,fanart,sketchbook]



# build settings
permalink: pretty

#used site plugins

#plugins:
# - jekyll-seo-tag